site_name: James's Blog
site_author: James McGill
repo_url: https://github.com/v1ster/repository
repo_name: v1ster/repository

theme:
  name: material
  icon:
    # logo: assets/
    logo: octicons/plug-16
    repo: simple/github
  palette:
    scheme: slate
    primary: black
    accent: lime
  features:
    - content.code.copy
    - navigation.sections
    - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
plugins:
  - search
  - tags:
      tags_file: blog/tags.md

  - blog:
      blog_dir: .
      post_url_format: "{slug}"


markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - index.md
  - blog/tags.md
  - Blog:
    - blog/index.md
